# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('TOPUP_SUCCESS', 'Top-up Successful'), ('LOW_BALANCE', 'Low Balance Alert'), ('SYSTEM', 'System Update'), ('WITHDRAWAL_PENDING', 'Withdrawal Initiated'), ('WITHDRAWAL_SUCCESS', 'Withdrawal Successful'), ('WITHDRAWAL_FAILED', 'Withdrawal Failed'), ('DEPOSIT_PENDING', 'Deposit Initiated'), ('DEPOSIT_SUCCESS', 'Deposit Successful'), ('DEPOSIT_FAILED', 'Deposit Failed')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
