# Generated by Django 6.0.2 on 2026-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='mpesatransaction_amount_non_negative'),
        ),
    ]
