# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('mpesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_wallet', models.CharField(choices=[('MEAL', 'Meal Wallet'), ('POCKET', 'Pocket Wallet'), ('PERSONAL', 'Personal Wallet')], default='PERSONAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgerentry')),
                ('mpesa_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpesa.mpesatransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
