# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_value', models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('USED', 'USED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='guardians.customer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('student__isnull', False)), fields=('student',), name='one_active_qr_per_student'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('status', 'ACTIVE')), fields=('customer',), name='one_active_qr_per_customer')],
            },
        ),
    ]
