# Generated by Django 6.0.2 on 2026-03-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0003_alter_customerstudent_customer_and_more'),
        ('qrtokens', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='guardians.customer'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='students.student'),
        ),
    ]
