# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('account_type', models.CharField(choices=[('STUDENT_MEAL', 'Student Meal Wallet'), ('STUDENT_POCKET', 'Student Pocket Wallet'), ('CUSTOMER_MAIN', 'Guardian Primary Wallet'), ('BUSINESS_PAYOUT', 'Business Settlement Account'), ('PLATFORM_REVENUE', 'EasyPay Revenue Account')], max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'unique_together': {('owner_id', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('POSTED', 'POSTED'), ('REVERSED', 'REVERSED')], default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='ledger.ledgeraccount')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='ledger.ledgeraccount')),
            ],
        ),
    ]
