# Generated by Django 6.0.2 on 2026-02-27 14:01

from django.db import migrations
# We import the constant from your models to ensure they match exactly
from ledger.models import SYSTEM_PLATFORM_ID 

def create_system_entities(apps, schema_editor):
    LedgerAccount = apps.get_model('ledger', 'LedgerAccount')
    Wallet = apps.get_model('wallets', 'Wallet')
    
    # We use the constant here. If it's 32 zeros in models.py, 
    # it will be 32 zeros here automatically.
    SYSTEM_ID = SYSTEM_PLATFORM_ID

    # 1. Create the System Ledger Account
    LedgerAccount.objects.get_or_create(
        owner_id=SYSTEM_ID,
        account_type="PLATFORM_REVENUE",
        defaults={'balance': 0.00}
    )

    # 2. Create the System Wallet
    Wallet.objects.get_or_create(
        owner_id=SYSTEM_ID,
        owner_type="PLATFORM",
        type="REVENUE",
        defaults={'balance': 0.00, 'is_withdrawable': True}
    )

class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_system_entities),
    ]
