# Generated by Django 6.0.2 on 2026-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20260227_1701'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='ledgeraccount_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledgerentry_amount_positive'),
        ),
    ]
