# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('CUSTOMER', 'CUSTOMER')], max_length=20)),
                ('payer_id', models.UUIDField()),
                ('wallet_type', models.CharField(choices=[('MEAL', 'MEAL'), ('POCKET', 'POCKET'), ('PERSONAL', 'PERSONAL'), ('SETTLEMENT', 'SETTLEMENT'), ('REVENUE', 'REVENUE')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=3.0, max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.business')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgerentry')),
                ('payment_intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentintent')),
            ],
        ),
    ]
