# Generated by Django 6.0.2 on 2026-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgeraccount_ledgeraccount_balance_non_negative_and_more'),
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('payment_intent',), name='uniq_transaction_per_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__gte', 0)), name='transaction_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__lte', models.F('amount'))), name='transaction_fee_not_exceed_amount'),
        ),
    ]
