# Generated by Django 6.0.2 on 2026-03-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('transactions', '0002_transaction_uniq_transaction_per_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.business'),
        ),
    ]
