# Generated by Django 6.0.2 on 2026-02-27 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('MATCHED', 'MATCHED'), ('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('payer_id', models.UUIDField(blank=True, null=True)),
                ('payer_type', models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('CUSTOMER', 'CUSTOMER')], max_length=20, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.business')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.businessterminal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('terminal',), name='one_pending_intent_per_terminal')],
            },
        ),
    ]
