from django.contrib import admin
from django.utils import timezone
from .models import QRToken

@admin.register(QRToken)
class QRTokenAdmin(admin.ModelAdmin):
    # 1. Quick identification of tokens in the field
    list_display = (
        'token_preview', 
        'owner_display', 
        'amount', 
        'status', 
        'is_live', 
        'expires_at'
    )
    
    # 2. Vital filters for monitoring token usage
    list_filter = ('status', 'created_at')
    
    # 3. Search by the secret value or the owner's details
    search_fields = (
        'token_value', 
        'student__user__first_name', 
        'student__reg_no', 
        'customer__user__phone'
    )
    
    # 4. Security: Prevent manual creation of tokens in Admin
    # Tokens should only be generated by the mobile app logic
    readonly_fields = ('token_value', 'created_at')

    # 5. Actions for high-security scenarios
    actions = ['deactivate_tokens']

    # --- Custom Display Methods ---

    def token_preview(self, obj):
        return f"{obj.token_value[:8]}..."
    token_preview.short_description = "Token ID"

    def owner_display(self, obj):
        if obj.student:
            return f"Student: {obj.student.user.first_name}"
        return f"Guardian: {obj.customer.user.phone}"
    owner_display.short_description = "Owner"

    def is_live(self, obj):
        """Visual indicator if the QR is currently usable"""
        return obj.is_valid
    is_live.boolean = True
    is_live.short_description = "Valid?"

    # --- Custom Actions ---

    @admin.action(description="Revoke selected tokens (Mark as EXPIRED)")
    def deactivate_tokens(self, request, queryset):
        updated = queryset.update(status="EXPIRED")
        self.message_user(request, f"{updated} tokens were successfully revoked.")
