# Generated by Django 6.0.2 on 2026-03-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0002_alter_customerstudent_student'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstudent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_students', to='guardians.customer'),
        ),
        migrations.AlterField(
            model_name='customerstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
