# Generated by Django 6.0.2 on 2026-02-27 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('CUSTOMER', 'CUSTOMER'), ('BUSINESS', 'BUSINESS'), ('PLATFORM', 'PLATFORM')], max_length=20)),
                ('owner_id', models.UUIDField()),
                ('type', models.CharField(choices=[('MEAL', 'MEAL'), ('POCKET', 'POCKET'), ('PERSONAL', 'PERSONAL'), ('SETTLEMENT', 'SETTLEMENT'), ('REVENUE', 'REVENUE')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawable', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('owner_type', 'owner_id', 'type')},
            },
        ),
    ]
