# Generated by Django 6.0.2 on 2026-03-04 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgeraccount_ledgeraccount_balance_non_negative_and_more'),
        ('withdrawal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='withdrawal_fee_non_negative'),
        ),
    ]
